### ISSUE TITLE
사용자 모델 생성 방법 정리

### ISSUE THREAD

**Issue by 9bow** [shineware/KOMORANAdmin#14]
## 기능 설명
#13 을 위해, 사용자가 변경한 사용자 사전, 단어 빈도, 품사 빈도 및 기분석 사전을 반영한 사용자 모델을
어떻게 생성하는지 정리가 필요합니다.

## 추가 정보
필요 시, [KOMORAN 문서](http://docs.komoran.kr/examples/train-model.html)도 함께 갱신합니다.

**Comment by 9bow** [comment]
@shin285 확인 및 정리 부탁드립니다.

**Comment by shin285** [comment]
모델생성 예제 코드레벨로 추가하겠습니다

**Comment by shin285** [comment]
```java
        ModelBuilder modelBuilder = new ModelBuilder();
        modelBuilder.buildPath("corpus_build");
        modelBuilder.save("models_full");
```

**Comment by 9bow** [comment]
위와 같이 모델 생성 후, 생성된 모델을 불러와 UserDic과 FWDic을 적용합니다.

모델 생성 시, corpus_build 내의 불규칙 사전은 미리 포함되어 있어야 합니다.
