### ISSUE TITLE
윈도우에서 기능 동작 여부 확인

### ISSUE THREAD

**Issue by shin285** [shineware/KOMORANAdmin#18]
## 기능 설명
윈도우에서 각 기능이 정상적으로 동작하는지 확인
- [ ] 사전 업로드
- [x] 사전 다운로드
- [ ] 사용자 사전 수정
- [ ] 기분석 사전 수정
- [ ] 형태소 분석 결과 비교

## 추가 정보
N/A

**Comment by 9bow** [comment]
@shin285 
지난 주말에 작업한 기분석 사전 관련 내용(#7)을 곧 올리도록 하겠습니다. (아직 Front-end 작업이 완료되지 않았습니다;; ) 위 내용 중 `기분석 사전 수정`은 해당 커밋 이후에 테스트 부탁드립니다.

**Comment by 9bow** [comment]
#21 에 기분석 사전 관련 내용을 포함한 PR을 올렸습니다.

**Comment by 9bow** [comment]
v0.9.5(#25)에서 추가된 사전 배포 메뉴에서 다음과 같은 내용의 확인이 필요합니다.

아래 이미지 중 `3`에서 `modelBaseDir` 경로가 OS에 따라 다르게 표시되어야 합니다.
* Windows 계열인 경우: `"C:\\Some\\Path\\To\\Komoran\\"`
* macOS 및 Linux 계열인 경우: "/Some/Path/To/Komoran/"

![image](https://user-images.githubusercontent.com/9343724/64704714-b0314c00-d4e9-11e9-853f-ccc3352c9c55.png)

**Comment by 9bow** [comment]
@shin285 
윈도우 환경에서 테스트 부탁드립니다. (_ _)

**Comment by shin285** [comment]
- [ ] 사전 업로드에서 파일 선택 후 업로드 버튼을 누르면 "Unknown Error" 발생
![image](https://user-images.githubusercontent.com/8907756/64924688-243d5e00-d822-11e9-893d-fb67a9fbc1b2.png)

- [ ] 사용자 사전에 "아차산역"을 "NNP"로 추가하고 모델 생성 후 "아차산역에서 공 찼어."라고 형태소 분석 비교 시 "찼어."가 "NA"가 되는 문제 발생
![image](https://user-images.githubusercontent.com/8907756/64924677-1091f780-d822-11e9-86af-eb49ad83c873.png)

- [ ] 기분석 사전에 "찼어로드에서 파일 선택 후 업로드 버튼을 누르면 "Unknown Error" 발생
![image](https://user-images.githubusercontent.com/8907756/64924688-243d5e00-d822-11e9-893d-fb67a9fbc1b2.png)

- [ ] 사용자 사전에 "아차산역"을 "NNP"로 추가하고 모델 생성 후 "아차산역에서 공 찼어."라고 형태소 분석 비교 시 "찼어."가 "NA"가 되는 문제 발생
![image](https://user-images.githubusercontent.com/8907756/64924677-1091f780-d822-11e9-86af-eb49ad83c873.png)

- [ ] 기분석 사전에 "공찼어"를 "공/NNG 찼어/NNG"로 추가하고 모덷ㄹ 생성 후 "아차산역에서 공찼어"라고 형태소 분석 비교 시 "찼어"가 NNG가 되는 문제 발생
![image](https://user-images.githubusercontent.com/8907756/64924766-f3115d80-d822-11e9-948e-3bf12e46a5aa.png)

- [ ] 사전 다운로드 시 파일의 인코딩이 UTF-8인지 확인 필요. UTF-8로 오픈 시 문자 깨짐 현상 발생

**Comment by 9bow** [comment]
@shin285 
테스트 감사합니다.
1번은 크롬 개발자 콘솔에서도 아무런 에러가 발생하지 않나요? 환경과 사전의 종류와 테스트하셨던 파일을 전달해주시면 테스트 해보도록 하겠습니다.
2-3번은 만나서 같이 확인이 필요할 것 같습니다.
4번은 확인해보고 다시 알려드리겠습니다. 환경과 다운로드 받으셨던 파일을 전달해주시면 도움이 될 것 같습니다.

**Comment by 9bow** [comment]
4번 이슈는 macOS에서는 아래와 같이 UTF-8 파일로 확인됩니다. (기분석 사전 기준)
![image](https://user-images.githubusercontent.com/9343724/64925357-784c4080-d82a-11e9-913d-1268c6425619.png)

윈도우즈 환경이시라면 환경 변수에 인코딩 옵션을 넣고 테스트 부탁드립니다.
(옵션을 넣고 테스트 시 정상적으로 동작한다면 Spring Boot 설정 등에서 강제할 수 있도록 하겠습니다.)

**Comment by shin285** [comment]
일단 테스트 해보지 않았지만 별도의 설정이 안되어 있다면 시스템 인코딩을 따라갑니다. gradle과 springboot를 UTF8로 강제하는 것이 좋을 것 같습니다.

**Comment by 9bow** [comment]
1번 이슈는 재현이 되지 않아 1.0에서는 이슈를 닫습니다. 재현 시 다시 열어주시기를 부탁드립니다.
2번 이슈는 KOMORAN 3.3.5로 개선되었습니다. https://github.com/shin285/KOMORAN/commit/7bba1e0b8278b25c8dcd7fb53102769ee1706422

**Comment by 9bow** [comment]
@shin285 
이슈 내용의 테스트 항목에 대한 피드백 요청드립니다.

**Comment by 9bow** [comment]
2번 이슈 KOMORAN 업데이트 후 테스트 결과입니다.

![image](https://user-images.githubusercontent.com/9343724/65047578-a8682080-d99d-11e9-97ac-f6adb5c5d511.png)
