### ISSUE TITLE
사용자 사전과 기분석 사전의 기본 내용 정리

### ISSUE THREAD

**Issue by 9bow** [shineware/KOMORANAdmin#26]
## 기능 설명
현재 `단어 빈도(dic.word)`와 `품사 빈도(grammar.in)`은 존재하지 않을 경우 기본 내용으로 KOMORAN의 것들이 채워집니다.
`사용자 사전(dic.user)`와 `기분석 사전(fwd.user)`의 경우에는 어떠한 기본 내용을 채울 것인지 정리가 필요합니다.

## 추가 정보
_N/A_

**Comment by 9bow** [comment]
이 내용은 처음으로 KOMORAN 관리도구를 실행했을 때 포함되어야 하는 내용으로, 사용자 시나리오 작성을 위한 데이터(#19)와는 다른 종류입니다.

**Comment by shin285** [comment]
사용자 사전과 기분석 사전은 기본 내용이 없는 상태가 기본값입니다.
